# Generated by Django 5.2.15 on 2026-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userprofile_default_pathology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='entertainment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='hospital',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='nature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='nightlife',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tourism',
            field=models.FloatField(default=0),
        ),
    ]
